/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penujualan_tiket_kereta_api;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ACER
 */
public class Beranda extends javax.swing.JFrame {
    int sibinuang, bandara, harga, beli, total, bayar, kembali;
    private Integer a;
    private Integer b;
    private int c;
    ButtonGroup group;
    private String metodePembayaran;
    private boolean isPaid = false;
    



    /**
     * Creates new form tiket_kereta
     */
    public Beranda() {
        initComponents();
        group = new ButtonGroup();
        group.add(rb_vip);
        group.add(rb_ekonomi);
        
        
         Date date = new Date();
        tanggal.setDate(date); 
       
        btn_cetak.setEnabled(false);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jurusan = new javax.swing.JComboBox<>();
        rb_vip = new javax.swing.JRadioButton();
        rb_ekonomi = new javax.swing.JRadioButton();
        txt_harga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        txt_nomor = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        bbelilagi = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        Btn_pembayaran = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Selamat Datang");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel11.setText("Mau Kemana Anda Hari Ini ?");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(0, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kereta"));

        jLabel2.setText("Jurusan");

        jLabel3.setText("Jenis");

        jLabel4.setText("Harga");

        jurusan.setBackground(new java.awt.Color(255, 204, 255));
        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "       --- Pilih ---", "Alai (AI)", "Air Tawar (ATR)", "Tabing (TAB)", "Lubuk Buaya (LBY)" }));
        jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanActionPerformed(evt);
            }
        });

        rb_vip.setText("KA Sibinuang");
        rb_vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vipActionPerformed(evt);
            }
        });

        rb_ekonomi.setText("KA Bandara");
        rb_ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ekonomiActionPerformed(evt);
            }
        });

        txt_harga.setBackground(new java.awt.Color(255, 204, 255));

        jLabel13.setText("Tanggal");

        tanggal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_vip)
                            .addComponent(rb_ekonomi)
                            .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txt_harga, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rb_vip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(rb_ekonomi)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 102));

        txt_nomor.setBackground(new java.awt.Color(255, 204, 255));

        txt_nama.setBackground(new java.awt.Color(255, 204, 255));

        txt_jumlah.setBackground(new java.awt.Color(255, 204, 255));
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });

        txt_total.setBackground(new java.awt.Color(255, 204, 255));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_totalKeyReleased(evt);
            }
        });

        txt_bayar.setBackground(new java.awt.Color(255, 204, 255));
        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });

        txt_kembalian.setBackground(new java.awt.Color(255, 204, 255));
        txt_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembalianActionPerformed(evt);
            }
        });
        txt_kembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kembalianKeyReleased(evt);
            }
        });

        jLabel5.setText("No Kursi");

        jLabel6.setText("Nama Penumpang");

        jLabel10.setText("Uang Kembali");

        jLabel9.setText("Total Bayar");

        jLabel8.setText("Uang Bayar");

        jLabel7.setText("Jumla Beli");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_cetak.setBackground(new java.awt.Color(0, 255, 102));
        btn_cetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        bbelilagi.setBackground(new java.awt.Color(0, 255, 102));
        bbelilagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bbelilagi.setText("Beli Lagi");
        bbelilagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbelilagiActionPerformed(evt);
            }
        });

        btn_keluar.setBackground(new java.awt.Color(255, 51, 51));
        btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Pemesanan Tiket");
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));

        btn_logout.setBackground(new java.awt.Color(0, 255, 102));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        Btn_pembayaran.setBackground(new java.awt.Color(0, 255, 102));
        Btn_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_pembayaran.setText("Bayar");
        Btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_pembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cetak)
                            .addComponent(Btn_pembayaran))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_keluar)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bbelilagi)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(30, 30, 30)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bbelilagi)
                            .addComponent(btn_cetak))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_logout)
                            .addComponent(Btn_pembayaran)
                            .addComponent(btn_keluar))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ekonomiActionPerformed
        // TODO add your handling code here:
        if(rb_ekonomi.isSelected()){
            txt_harga.setText(String.valueOf(bandara));
        }
    }//GEN-LAST:event_rb_ekonomiActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembalianActionPerformed

    private void jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanActionPerformed
        // TODO add your handling code here:
    if (jurusan.getSelectedItem().equals("Pilih Jurusan")) {
        txt_harga.setText("");
    } else if (jurusan.getSelectedItem().equals("Alai (AI)")) {
        sibinuang = 5000;
        bandara = 10000;
    } else if (jurusan.getSelectedItem().equals("Air Tawar (ATR)")) {
        sibinuang = 5000;
        bandara = 10000;
    } else if (jurusan.getSelectedItem().equals("Tabing (TAB)")) {
        sibinuang = 5000;
        bandara = 10000;
    }else if (jurusan.getSelectedItem().equals("Lubuk Buaya (LBY)")) {
        sibinuang = 5000;
        bandara = 10000;
    }
    
    }//GEN-LAST:event_jurusanActionPerformed

    private void rb_vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vipActionPerformed
        // TODO add your handling code here:
        if(rb_vip.isSelected()){
            txt_harga.setText(String.valueOf(sibinuang));
        }
    }//GEN-LAST:event_rb_vipActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
        beli = Integer.parseInt(txt_jumlah.getText());
        harga = Integer.parseInt(txt_harga.getText());
        total = beli * harga;
        txt_bayar.setText(String.valueOf(total));

    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
         bayar=Integer.parseInt(txt_total.getText());
        kembali=Integer.parseInt(txt_bayar.getText());
        total = bayar- total;
        txt_kembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txt_harga.getText());
        b=Integer.valueOf(txt_jumlah.getText());
        c=a*b;
        txt_bayar.setText(""+c);
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void txt_totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyReleased
        // TODO add your handling code here:
          try {
        if (!txt_total.getText().isEmpty() && !txt_bayar.getText().isEmpty()) {
            int uangDibayar = Integer.valueOf(txt_total.getText());    // Uang yang dibayar pelanggan
            int totalHarga = Integer.valueOf(txt_bayar.getText());     // Total yang harus dibayar
            int kembalian = uangDibayar - totalHarga;
            txt_kembalian.setText(String.valueOf(kembalian));
        }
    } catch (NumberFormatException e) {
        // Handle error jika input bukan angka
        txt_kembalian.setText("");
    }
    }//GEN-LAST:event_txt_totalKeyReleased

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Anda Yakin Keluar?", "Keluar", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
         dispose();
    }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
      try {
    // Validasi apakah pembayaran sudah dilakukan
    if (!isPaid) {
        JOptionPane.showMessageDialog(this, 
            "Pembayaran belum dilakukan! Silakan lakukan pembayaran terlebih dahulu.", 
            "Belum Bayar", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Format tanggal
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String formattedDate = sdf.format(tanggal.getDate());
    
    // Format waktu cetak
    SimpleDateFormat timeFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    String printTime = timeFormat.format(new Date());
    
    // Dapatkan jenis tiket yang dipilih
    String jenisKereta = "";
    if (rb_vip.isSelected()) {
        jenisKereta = "Sibinuang";
    } else if (rb_ekonomi.isSelected()) {
        jenisKereta = "bandara";
    }
    
    // Format nilai mata uang
    int totalBayar = Integer.parseInt(txt_bayar.getText());
    int uangBayar = Integer.parseInt(txt_total.getText());
    int kembalian = Integer.parseInt(txt_kembalian.getText());
    
    // Buat tiket
    String tiket = "=" .repeat(50) + "\n" +
                  "           TIKET KERETA API\n" +
                  "=" .repeat(50) + "\n" +
                  "Nomor Kursi        : " + txt_nomor.getText() + "\n" +
                  "Nama Penumpang     : " + txt_nama.getText() + "\n" +
                  "Jurusan            : " + jurusan.getSelectedItem().toString() + "\n" +
                  "Jenis Tiket        : " + jenisKereta + "\n" +
                  "Tanggal Keberangkatan : " + formattedDate + "\n" +
                  "Jumlah Tiket       : " + txt_jumlah.getText() + "\n" +
                  "Harga per Tiket    : Rp " + String.format("%,d", Integer.parseInt(txt_harga.getText())) + "\n" +
                  "-" .repeat(50) + "\n" +
                  "Total Bayar        : Rp " + String.format("%,d", totalBayar) + "\n" +
                  "Uang Bayar         : Rp " + String.format("%,d", uangBayar) + "\n" +
                  "Uang Kembalian     : Rp " + String.format("%,d", kembalian) + "\n" +
                  "Metode Pembayaran  : " + (metodePembayaran != null ? metodePembayaran : "Tunai") + "\n" +
                  "-" .repeat(50) + "\n" +
                  "Waktu Cetak        : " + printTime + "\n" +
                  "=" .repeat(50) + "\n" +
                  "  Terima kasih telah menggunakan\n" +
                  "       layanan kami!\n" +
                  "=" .repeat(50);
        
    // Tampilkan tiket
    JOptionPane.showMessageDialog(this, tiket, "Tiket Kereta Api", JOptionPane.INFORMATION_MESSAGE);
    
    // Dialog pilihan format unduh
    String[] pilihan = {"Unduh sebagai Laporan PDF", "Unduh sebagai File Teks", "Tidak Unduh"};
    int pilihanUnduh = JOptionPane.showOptionDialog(this,
        "Pilih format untuk mengunduh struk:",
        "Unduh Laporan Struk",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        pilihan,
        pilihan[0]);
    
    switch (pilihanUnduh) {
        case 0: // PDF
            unduhLaporanPDF(tiket, formattedDate, printTime);
            break;
        case 1: // Text
            unduhLaporanTeks(tiket);
            break;
        case 2: // Tidak unduh
            break;
    }
    
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, 
        "Error: Format data tidak valid!", 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, 
        "Error saat mencetak: " + e.getMessage(), 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
}
    }
// Method untuk mengunduh laporan dalam format PDF
private void unduhLaporanPDF(String tiket, String tanggalKeberangkatan, String waktuCetak) {
    try {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        
        // Set nama file default
        String fileName = "Laporan_Tiket_" + txt_nomor.getText() + "_" + 
                         new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".html";
        fileChooser.setSelectedFile(new java.io.File(fileName));
        
        // Set filter untuk file HTML (sebagai alternatif PDF)
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("HTML Files (*.html)", "html");
        fileChooser.setFileFilter(filter);
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            
            if (!fileToSave.getName().toLowerCase().endsWith(".html")) {
                fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".html");
            }
            
            // Buat laporan HTML yang dapat dicetak sebagai PDF
            String laporanHTML = buatLaporanHTML(tanggalKeberangkatan, waktuCetak);
            
            java.io.FileWriter file = new java.io.FileWriter(fileToSave);
            file.write(laporanHTML);
            file.close();
            
            JOptionPane.showMessageDialog(this, 
                "Laporan berhasil dibuat dalam format HTML!\n" + 
                "Lokasi: " + fileToSave.getAbsolutePath() + "\n\n" +
                "Untuk mengkonversi ke PDF:\n" +
                "1. Buka file HTML di browser\n" +
                "2. Klik Print atau Ctrl+P\n" +
                "3. Pilih 'Save as PDF'", 
                "Laporan Berhasil Dibuat", 
                JOptionPane.INFORMATION_MESSAGE);
                
            // Buka file otomatis
            bukaFile(fileToSave);
        }
        
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, 
            "Gagal membuat laporan: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}

// Method untuk mengunduh laporan dalam format teks terstruktur
private void unduhLaporanTeks(String tiket) {
    try {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        
        String fileName = "Laporan_Tiket_" + txt_nomor.getText() + "_" + 
                         new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".txt";
        fileChooser.setSelectedFile(new java.io.File(fileName));
        
        javax.swing.filechooser.FileNameExtensionFilter filter = 
            new javax.swing.filechooser.FileNameExtensionFilter("Text Files (*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            
            if (!fileToSave.getName().toLowerCase().endsWith(".txt")) {
                fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".txt");
            }
            
            // Buat laporan teks yang lebih terstruktur
            String laporanTeks = buatLaporanTeks();
            
            java.io.FileWriter file = new java.io.FileWriter(fileToSave);
            file.write(laporanTeks);
            file.close();
            
            JOptionPane.showMessageDialog(this, 
                "Laporan teks berhasil dibuat!\n" + 
                "Lokasi: " + fileToSave.getAbsolutePath(), 
                "Laporan Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
                
            bukaFile(fileToSave);
        }
        
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, 
            "Gagal membuat laporan: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}

// Method untuk membuat laporan HTML yang profesional
private String buatLaporanHTML(String tanggalKeberangkatan, String waktuCetak) {
    SimpleDateFormat headerDate = new SimpleDateFormat("EEEE, dd MMMM yyyy", new java.util.Locale("id", "ID"));
    String tanggalLaporan = headerDate.format(new Date());
    
    return "<!DOCTYPE html>\n" +
           "<html>\n" +
           "<head>\n" +
           "    <meta charset='UTF-8'>\n" +
           "    <title>Transaksi Tiket Kereta Api</title>\n" +
           "    <style>\n" +
           "        body { font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }\n" +
           "        .container { background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }\n" +
           "        .header { text-align: center; border-bottom: 3px solid #2c3e50; padding-bottom: 20px; margin-bottom: 30px; }\n" +
           "        .header h1 { color: #2c3e50; margin: 0; font-size: 28px; }\n" +
           "        .header h2 { color: #7f8c8d; margin: 5px 0; font-size: 16px; font-weight: normal; }\n" +
           "        .info-section { margin: 20px 0; }\n" +
           "        .info-title { background-color: #3498db; color: white; padding: 10px; margin: 0; font-size: 16px; }\n" +
           "        .info-content { border: 1px solid #3498db; padding: 20px; margin: 0; }\n" +
           "        .data-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #ecf0f1; }\n" +
           "        .data-label { font-weight: bold; color: #2c3e50; width: 40%; }\n" +
           "        .data-value { color: #34495e; width: 60%; text-align: right; }\n" +
           "        .financial-section { background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin: 20px 0; }\n" +
           "        .total-row { font-size: 18px; font-weight: bold; color: #e74c3c; }\n" +
           "        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 2px solid #bdc3c7; }\n" +
           "        .print-info { color: #7f8c8d; font-size: 12px; margin-top: 20px; }\n" +
           "        @media print { body { background-color: white; } .container { box-shadow: none; } }\n" +
           "    </style>\n" +
           "</head>\n" +
           "<body>\n" +
           "    <div class='container'>\n" +
           "        <div class='header'>\n" +
           "            <h1>TRANSAKSI TIKET KERETA API</h1>\n" +
           "            <h2>Tanggal Laporan: " + tanggalLaporan + "</h2>\n" +
           "        </div>\n" +
           "\n" +
           "        <div class='info-section'>\n" +
           "            <h3 class='info-title'>INFORMASI PENUMPANG</h3>\n" +
           "            <div class='info-content'>\n" +
           "                <div class='data-row'>\n" +
           "                    <span class='data-label'>Nomor Kursi:</span>\n" +
           "                    <span class='data-value'>" + txt_nomor.getText() + "</span>\n" +
           "                </div>\n" +
           "                <div class='data-row'>\n" +
           "                    <span class='data-label'>Nama Penumpang:</span>\n" +
           "                    <span class='data-value'>" + txt_nama.getText() + "</span>\n" +
           "                </div>\n" +
           "                <div class='data-row'>\n" +
           "                    <span class='data-label'>Jurusan:</span>\n" +
           "                    <span class='data-value'>" + jurusan.getSelectedItem().toString() + "</span>\n" +
           "                </div>\n" +
           "                <div class='data-row'>\n" +
           "                    <span class='data-label'>Jenis Kereta:</span>\n" +
           "                    <span class='data-value'>" + (rb_vip.isSelected() ? "Sibinuang" : "Bandara") + "</span>\n" +
           "                </div>\n" +
           "                <div class='data-row'>\n" +
           "                    <span class='data-label'>Tanggal Keberangkatan:</span>\n" +
           "                    <span class='data-value'>" + tanggalKeberangkatan + "</span>\n" +
           "                </div>\n" +
           "                <div class='data-row'>\n" +
           "                    <span class='data-label'>Jumlah Tiket:</span>\n" +
           "                    <span class='data-value'>" + txt_jumlah.getText() + " tiket</span>\n" +
           "                </div>\n" +
           "            </div>\n" +
           "        </div>\n" +
           "\n" +
           "        <div class='info-section'>\n" +
           "            <h3 class='info-title'>RINCIAN PEMBAYARAN</h3>\n" +
           "            <div class='info-content'>\n" +
           "                <div class='financial-section'>\n" +
           "                    <div class='data-row'>\n" +
           "                        <span class='data-label'>Harga per Tiket:</span>\n" +
           "                        <span class='data-value'>Rp " + String.format("%,d", Integer.parseInt(txt_harga.getText())) + "</span>\n" +
           "                    </div>\n" +
           "                    <div class='data-row total-row'>\n" +
           "                        <span class='data-label'>Total Bayar:</span>\n" +
           "                        <span class='data-value'>Rp " + String.format("%,d", Integer.parseInt(txt_bayar.getText())) + "</span>\n" +
           "                    </div>\n" +
           "                    <div class='data-row'>\n" +
           "                        <span class='data-label'>Uang Bayar:</span>\n" +
           "                        <span class='data-value'>Rp " + String.format("%,d", Integer.parseInt(txt_total.getText())) + "</span>\n" +
           "                    </div>\n" +
           "                    <div class='data-row'>\n" +
           "                        <span class='data-label'>Uang Kembalian:</span>\n" +
           "                        <span class='data-value'>Rp " + String.format("%,d", Integer.parseInt(txt_kembalian.getText())) + "</span>\n" +
           "                    </div>\n" +
           "                    <div class='data-row'>\n" +
           "                        <span class='data-label'>Metode Pembayaran:</span>\n" +
           "                        <span class='data-value'>" + (metodePembayaran != null ? metodePembayaran : "Tunai") + "</span>\n" +
           "                    </div>\n" +
           "                </div>\n" +
           "            </div>\n" +
           "        </div>\n" +
           "\n" +
           "        <div class='footer'>\n" +
           "            <p><strong>Terima kasih telah menggunakan layanan kami!</strong></p>\n" +
           "            <div class='print-info'>\n" +
           "                <p>Waktu Cetak: " + waktuCetak + "</p>\n" +
           "                <p>Dokumen ini digenerate secara otomatis oleh sistem</p>\n" +
           "            </div>\n" +
           "        </div>\n" +
           "    </div>\n" +
           "</body>\n" +
           "</html>";
}

// Method untuk membuat laporan teks terstruktur
private String buatLaporanTeks() {
    SimpleDateFormat headerDate = new SimpleDateFormat("EEEE, dd MMMM yyyy HH:mm:ss", new java.util.Locale("id", "ID"));
    String waktuLaporan = headerDate.format(new Date());
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    String tanggalBerangkat = sdf.format(tanggal.getDate());
    
    return "╔" + "═".repeat(60) + "╗\n" +
           "║" + " ".repeat(15) + "LAPORAN TRANSAKSI TIKET KERETA API" + " ".repeat(11) + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║ Tanggal Laporan: " + String.format("%-41s", waktuLaporan) + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║" + " ".repeat(20) + "INFORMASI PENUMPANG" + " ".repeat(20) + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║ Nomor Kursi        : " + String.format("%-35s", txt_nomor.getText()) + "║\n" +
           "║ Nama Penumpang     : " + String.format("%-35s", txt_nama.getText()) + "║\n" +
           "║ Jurusan            : " + String.format("%-35s", jurusan.getSelectedItem().toString()) + "║\n" +
           "║ Jenis Kereta       : " + String.format("%-35s", (rb_vip.isSelected() ? "Sibinuang" : "Bandara")) + "║\n" +
           "║ Tanggal Keberangkatan : " + String.format("%-32s", tanggalBerangkat) + "║\n" +
           "║ Jumlah Tiket       : " + String.format("%-35s", txt_jumlah.getText() + " tiket") + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║" + " ".repeat(21) + "RINCIAN PEMBAYARAN" + " ".repeat(21) + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║ Harga per Tiket    : " + String.format("%35s", "Rp " + String.format("%,d", Integer.parseInt(txt_harga.getText()))) + "║\n" +
           "║ Total Bayar        : " + String.format("%35s", "Rp " + String.format("%,d", Integer.parseInt(txt_bayar.getText()))) + "║\n" +
           "║ Uang Bayar         : " + String.format("%35s", "Rp " + String.format("%,d", Integer.parseInt(txt_total.getText()))) + "║\n" +
           "║ Uang Kembalian     : " + String.format("%35s", "Rp " + String.format("%,d", Integer.parseInt(txt_kembalian.getText()))) + "║\n" +
           "║ Metode Pembayaran  : " + String.format("%-35s", (metodePembayaran != null ? metodePembayaran : "Tunai")) + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║" + " ".repeat(13) + "Terima kasih telah menggunakan" + " ".repeat(17) + "║\n" +
           "║" + " ".repeat(23) + "layanan kami!" + " ".repeat(23) + "║\n" +
           "╠" + "═".repeat(60) + "╣\n" +
           "║ Waktu Cetak: " + String.format("%-45s", waktuLaporan) + "║\n" +
           "║ Dokumen ini digenerate secara otomatis oleh sistem" + " ".repeat(9) + "║\n" +
           "╚" + "═".repeat(60) + "╝\n\n" +
           "CATATAN:\n" +
           "- Simpan dokumen ini sebagai bukti transaksi\n" +
           "- Tunjukkan tiket saat keberangkatan\n" +
           "- Datang minimal 30 menit sebelum keberangkatan\n" +
           "\n" +
           "═".repeat(62) + "\n" +
           "Sistem Informasi Tiket Kereta API v1.0\n" +
           "© 2024 - Semua hak cipta dilindungi\n" +
           "═".repeat(62);
}

// Method untuk membuka file
private void bukaFile(java.io.File file) {
    try {
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.OPEN)) {
                desktop.open(file);
            }
        }
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this,
            "Gagal membuka file: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }

          
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void txt_kembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kembalianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembalianKeyReleased

    private void bbelilagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbelilagiActionPerformed
        // TODO add your handling code here:
      txt_harga.setText("");
    txt_nomor.setText("");
    txt_nama.setText("");
    txt_jumlah.setText("");
    txt_total.setText("");
    txt_bayar.setText("");
    txt_kembalian.setText("");
    jurusan.setSelectedIndex(0);
    
    
    group.clearSelection();
    this.isPaid = false;
    this.metodePembayaran = null;
    btn_cetak.setEnabled(false);
    
    // Set tanggal ke hari ini
    Date date = new Date();
    tanggal.setDate(date);
    }//GEN-LAST:event_bbelilagiActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin logout?.",
        "Konfirmasi Logout",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
        // Jika user memilih YES
    if (confirm == JOptionPane.YES_OPTION) {
        
        // Tampilkan pesan logout berhasil
        JOptionPane.showMessageDialog(
            this,
            "Logout berhasil!\nTerima kasih telah menggunakan aplikasi kami.",
            "Logout Berhasil",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        // Tutup form beranda
        this.dispose();
        
        // Buka form login
        try {
            Login loginForm = new Login();
            loginForm.setVisible(true);
            
        } catch (Exception e) {
            // Jika class Login tidak ada, tampilkan pesan
            JOptionPane.showMessageDialog(
                null,
                "Form login tidak ditemukan.\nAplikasi akan ditutup.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            // Keluar dari aplikasi
            System.exit(0);
        }
    }
        
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void Btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_pembayaranActionPerformed
        // TODO add your handling code here:
       if (txt_nomor.getText().isEmpty() || txt_nama.getText().isEmpty() || 
        txt_jumlah.getText().isEmpty() || txt_harga.getText().isEmpty() ||
        jurusan.getSelectedItem().equals(" ")) {
        
        JOptionPane.showMessageDialog(this, 
            "Mohon lengkapi semua data pemesanan terlebih dahulu!", 
            "Data Tidak Lengkap", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
        // Validasi data pembayaran
    if (txt_total.getText().isEmpty() || txt_bayar.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Mohon isi jumlah uang bayar terlebih dahulu!", 
            "Data Pembayaran Tidak Lengkap", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        int totalHargaYangHarusDibayar = Integer.parseInt(txt_bayar.getText()); // Total dari harga x jumlah
        int uangYangDibayarkanPelanggan = Integer.parseInt(txt_total.getText()); // Uang yang dibayar pelanggan
        
        // Validasi apakah uang yang dibayar cukup
        if (uangYangDibayarkanPelanggan < totalHargaYangHarusDibayar) {
            JOptionPane.showMessageDialog(this, 
                "Uang yang dibayarkan kurang dari total yang harus dibayar!\n" +
                "Total yang harus dibayar: Rp " + String.format("%,d", totalHargaYangHarusDibayar) + "\n" +
                "Uang yang dibayarkan: Rp " + String.format("%,d", uangYangDibayarkanPelanggan), 
                "Pembayaran Tidak Cukup", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Hitung kembalian
        int kembalian = uangYangDibayarkanPelanggan - totalHargaYangHarusDibayar;
        txt_kembalian.setText(String.valueOf(kembalian));
        
        // Tampilkan dialog konfirmasi pembayaran
        String[] metodePembayaran = {"Tunai", "Transfer Bank", "E-Wallet", "Kartu Kredit"};
        String metode = (String) JOptionPane.showInputDialog(
            this,
            "Pilih metode pembayaran:",
            "Metode Pembayaran",
            JOptionPane.QUESTION_MESSAGE,
            null,
            metodePembayaran,
            metodePembayaran[0]
        );
        
        if (metode != null) {
        // Simpan metode pembayaran
            this.metodePembayaran = metode;
            this.isPaid = true;
            
        // Tampilkan konfirmasi pembayaran berhasil
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String waktuPembayaran = sdf.format(new Date());
            
            JOptionPane.showMessageDialog(this,
                "PEMBAYARAN BERHASIL!\n\n" +
                "Metode Pembayaran: " + metode + "\n" +
                "Total yang Harus Dibayar: Rp " + String.format("%,d", totalHargaYangHarusDibayar) + "\n" +
                "Uang yang Dibayarkan: Rp " + String.format("%,d", uangYangDibayarkanPelanggan) + "\n" +
                "Kembalian: Rp " + String.format("%,d", kembalian) + "\n" +
                "Waktu Pembayaran: " + waktuPembayaran + "\n\n" +
                "Terima kasih atas pembayaran Anda!",
                "Pembayaran Berhasil",
                JOptionPane.INFORMATION_MESSAGE
            );
            
        // Enable tombol cetak setelah pembayaran berhasil
            btn_cetak.setEnabled(true);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Format angka tidak valid! Pastikan semua input berupa angka.", 
            "Error Format", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}

        private boolean isPaymentCompleted() {
        return this.isPaid;
}


            private void resetPaymentStatus() {
            this.isPaid = false;
            this.metodePembayaran = null;
            btn_cetak.setEnabled(false);
            txt_kembalian.setText("");
    }//GEN-LAST:event_Btn_pembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_pembayaran;
    private javax.swing.JButton bbelilagi;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JRadioButton rb_ekonomi;
    private javax.swing.JRadioButton rb_vip;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nomor;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables


}
