/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penujualan_tiket_kereta_api;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
/**
 *
 * @author ACER
 */
public class Daftar extends javax.swing.JFrame {

    /**
     * Creates new form Registrasi
     */
    
    public static String username;
    public static String email;
    public static String no_telpon;
    public static String tanggal_lahir;
    public static String jenis_kelamin;
    public static String password;
    private ButtonGroup genderGroup;
    
    public Daftar() {
        initComponents();
        setLocationRelativeTo(null);
        
        genderGroup = new ButtonGroup();
        genderGroup.add(rblaki);
        genderGroup.add(rbperempuan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bsubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jnotelpon = new javax.swing.JTextField();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jtanggal = new com.toedter.calendar.JDateChooser();
        jPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bklik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");

        bsubmit.setBackground(new java.awt.Color(0, 255, 102));
        bsubmit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bsubmit.setText("Daftar Sekarang");
        bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("No Telpon");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Jenis Kelamin");

        rblaki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rblaki.setText("Laki - Laki");

        rbperempuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbperempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rblaki)
                        .addGap(26, 26, 26)
                        .addComponent(rbperempuan))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addComponent(jusername, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jemail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jnotelpon, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bsubmit)
                .addGap(185, 185, 185))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jnotelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rblaki, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbperempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(bsubmit)
                .addGap(34, 34, 34))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Daftar Akun");

        jLabel3.setText("Sudah punya akun KAI ?");

        bklik.setBackground(new java.awt.Color(0, 255, 102));
        bklik.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bklik.setText("Klik di Sini");
        bklik.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bklikFocusLost(evt);
            }
        });
        bklik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bklikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bklik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bklik))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bklikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bklikActionPerformed
        // TODO add your handling code here:
       this.dispose();
    new Login().setVisible(true);
    }//GEN-LAST:event_bklikActionPerformed

    private void bklikFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bklikFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bklikFocusLost

    private void bsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubmitActionPerformed
        // TODO add your handling code here:
   String inputUsername = jusername.getText().trim();
    String inputEmail = jemail.getText().trim();
    String inputNo_Telpon = jnotelpon.getText().trim();
    String inputTanggal_lahir = "";
    String inputJenis_Kelamin = "";
    
    // Perbaikan: Ambil tanggal dari JDateChooser dengan benar
    if (jtanggal.getDate() != null) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        inputTanggal_lahir = sdf.format(jtanggal.getDate());
    }
    
    // Cek radio button mana yang dipilih
    if (rblaki.isSelected()) {
        inputJenis_Kelamin = "Laki-laki";
    } else if (rbperempuan.isSelected()) {
        inputJenis_Kelamin = "Perempuan";
    }
    
    String inputPassword = jPassword.getText().trim();
    
    // Validasi input kosong - semua field harus diisi
    if(inputUsername.isEmpty() || inputEmail.isEmpty() || inputNo_Telpon.isEmpty() || 
       inputTanggal_lahir.isEmpty() || inputJenis_Kelamin.isEmpty() || inputPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Semua field harus diisi!", 
            "Error", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Validasi panjang username
    if(inputUsername.length() < 3) {
        JOptionPane.showMessageDialog(this, 
            "Username minimal 3 karakter!", 
            "Error", 
            JOptionPane.WARNING_MESSAGE);
        jusername.requestFocus();
        return;
    }
    
    // Perbaikan: Validasi email yang lebih robust
    String emailRegex = "^[A-Za-z0-9+_.-]+@([A-Za-z0-9.-]+\\.[A-Za-z]{2,})$";
    if(!inputEmail.matches(emailRegex)) {
        JOptionPane.showMessageDialog(this, 
            "Format email tidak valid!", 
            "Error", 
            JOptionPane.WARNING_MESSAGE);
        jemail.requestFocus();
        return;
    }
    
    // Perbaikan: Validasi nomor telepon dengan panjang yang masuk akal
    if(!inputNo_Telpon.matches("\\d{10,15}")) {
        JOptionPane.showMessageDialog(this, 
            "Nomor telepon harus berisi 10-15 digit angka!", 
            "Error", 
            JOptionPane.WARNING_MESSAGE);
        jnotelpon.requestFocus();
        return;
    }
    
    // Validasi panjang password
    if(inputPassword.length() < 6) {
        JOptionPane.showMessageDialog(this, 
            "Password minimal 6 karakter!", 
            "Error", 
            JOptionPane.WARNING_MESSAGE);
        jPassword.requestFocus();
        return;
    }
    
    // Perbaikan: Gunakan try-with-resources untuk auto-close connections
    String sqlCheck = "SELECT username FROM akun WHERE username = ?";
    String sqlInsert = "INSERT INTO akun (username, email, no_telpon, tanggal_lahir, jenis_kelamin, password) VALUES (?, ?, ?, ?, ?, ?)";
    
    try (Connection conn = koneksi.Ukoneksi();
         PreparedStatement pstCheck = conn.prepareStatement(sqlCheck)) {
        
        if (conn == null) {
            JOptionPane.showMessageDialog(this, 
                "Koneksi database gagal!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Cek apakah username sudah ada
        pstCheck.setString(1, inputUsername);
        try (ResultSet rs = pstCheck.executeQuery()) {
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, 
                    "Username sudah digunakan!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                jusername.requestFocus();
                return;
            }
        }
        
        // Insert user baru dengan semua field
        try (PreparedStatement pstInsert = conn.prepareStatement(sqlInsert)) {
            pstInsert.setString(1, inputUsername);
            pstInsert.setString(2, inputEmail);
            pstInsert.setString(3, inputNo_Telpon);
            pstInsert.setString(4, inputTanggal_lahir);
            pstInsert.setString(5, inputJenis_Kelamin);
            pstInsert.setString(6, inputPassword); // Note: Dalam production, hash password ini!
            
            int result = pstInsert.executeUpdate();
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, 
                    "Registrasi berhasil!\nSelamat datang " + inputUsername, 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Set static variables
                username = inputUsername;
                email = inputEmail;
                no_telpon = inputNo_Telpon;
                tanggal_lahir = inputTanggal_lahir;
                jenis_kelamin = inputJenis_Kelamin;
                password = inputPassword;
                
                // Tutup form registrasi dan buka form login
                this.dispose();
                new Login().setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Registrasi gagal!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch(SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Database Error: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } catch(Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + e.getMessage(), 
            "System Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_bsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bklik;
    private javax.swing.JButton bsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jnotelpon;
    private com.toedter.calendar.JDateChooser jtanggal;
    private javax.swing.JTextField jusername;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    // End of variables declaration//GEN-END:variables

    
}
